// src/components/NavRow.svelte
<script lang="ts">
	import { browser, prerendering } from '$app/env'
	import { page } from '$app/stores'
	import { onDestroy, onMount } from 'svelte'
	import { debounce } from 'throttle-debounce'

	interface Link {
		href: string
		label: string
	}

	export let links: Link[]
	/** Query param name to use (to not use queries, leave this prop blank) */
	export let query = ''

	export let noScroll: true | null = null

	/** Path level in URL, zero-indexed */
	export let level = 0

	let path: string[]
	$: path = [
		...$page.url.pathname
			.substring(1)
			.split('/')
			.map((route) => '/' + route),
		'/',
	]

	$: basePath = path.slice(0, level).join('')

	/* Animation */
	const FAST_TIMING = 'cubic-bezier(1,0,.3,1) -140ms'
	const SLOW_TIMING = 'cubic-bezier(.75,-0.01,.24,.99) -40ms'

	$: activeIndex = query
		? prerendering
			? -1
			: links.findIndex((link) => ($page.url.searchParams.get(query) || '') === link.href)
		: links.findIndex((link) => path[level] === link.href || path[level] === link.href.slice(0, -1))

	let oldIndex = -1

	const linkElements: HTMLAnchorElement[] = []

	const indicator = {
		left: 0,
		right: 0,
		top: 22,
		direction: 'right',
	}

	$: if (activeIndex > -1 && browser && linkElements.length > 0) startAnimation()

	function startAnimation() {
		// Avoids error that `linkElements[activeIndex]` is null
		if (linkElements[activeIndex]) {
			indicator.direction = activeIndex < oldIndex ? 'left' : 'right'

			indicator.left = linkElements[activeIndex].offsetLeft
			indicator.right =
				linkElements[activeIndex].parentElement.offsetWidth -
				linkElements[activeIndex].offsetLeft -
				linkElements[activeIndex].offsetWidth
			indicator.top =
				linkElements[activeIndex].offsetTop + linkElements[activeIndex].offsetHeight - 2
		}

		oldIndex = activeIndex
	}

	const debounced = debounce(100, startAnimation)

	let useAnimation = false

	onMount(() => {
		setTimeout(() => {
			useAnimation = true
		}, 300)

		window.addEventListener('resize', debounced)
	})

	onDestroy(() => {
		if (browser) window.removeEventListener('resize', debounced)
	})
</script>

<nav class="navigation" class:use-animation={useAnimation}>
	{#each links as link, index}
		<a
			href={query
				? link.href
					? `?${query}=${link.href}`
					: '?'
				: level === 0
				? link.href
				: basePath + link.href}
			class="navigation__link"
			class:is-active={index === activeIndex}
			sveltekit:noscroll={noScroll}
			sveltekit:prefetch
			bind:this={linkElements[index]}>
			{link.label}
		</a>
	{/each}
	<div
		class="navigation__indicator"
		style:visibility={useAnimation && activeIndex !== -1 ? 'visible' : 'hidden'}
		style:left={indicator.left + 'px'}
		style:right={indicator.right + 'px'}
		style:top={indicator.top + 'px'}
		style:transition={`left 350ms ${
			indicator.direction === 'left' ? FAST_TIMING : SLOW_TIMING
		},right 350ms ${
			indicator.direction === 'right' ? FAST_TIMING : SLOW_TIMING
		}, top 100ms ease-in-out`} />
</nav>

<style lang="postcss">
	.navigation {
		display: flex;
		flex-direction: row;
		align-items: center;
		grid-gap: 1rem;
		flex-wrap: wrap;
		position: relative;

		&__link {
			font-weight: var(--font-weight-bold);
			color: var(--color-text-light);
			position: relative;

			&::after {
				content: '';
				display: block;
				position: absolute;
				bottom: -2px;
				width: 100%;
				border-radius: var(--rounded-max);
				height: 0.25rem;
				transition: opacity 0.1s ease-in-out;
				background-color: var(--color-brand);
				opacity: 0;
			}

			&:hover {
				color: var(--color-text);

				&::after {
					opacity: 0.4;
				}
			}

			&:active::after {
				opacity: 0.2;
			}

			&.is-active {
				color: var(--color-text);

				&::after {
					opacity: 1;
				}
			}
		}

		&.use-animation {
			.navigation__link {
				&.is-active::after {
					opacity: 0;
				}
			}
		}

		&__indicator {
			position: absolute;
			height: 0.25rem;
			border-radius: var(--rounded-max);
			background-color: var(--color-brand);
			transition-property: left, right, top;
			transition-duration: 350ms;
			visibility: hidden;
		}
	}
</style>

// lib/components/nav/NavRow.vue
<template>
  <nav class="navigation">
    <router-link
      v-for="(link, index) in filteredLinks"
      v-show="link.shown === undefined ? true : link.shown"
      :key="index"
      ref="linkElements"
      :to="query ? (link.href ? `?${query}=${link.href}` : '?') : link.href"
      class="nav-link button-animation"
    >
      <span>{{ link.label }}</span>
    </router-link>
    <div
      class="nav-indicator"
      :style="{
        left: positionToMoveX,
        top: positionToMoveY,
        width: sliderWidth,
        opacity: activeIndex === -1 ? 0 : 1,
      }"
      aria-hidden="true"
    />
  </nav>
</template>

<script>
export default {
  props: {
    links: {
      default: () => [],
      type: Array,
    },
    query: {
      default: null,
      type: String,
    },
  },
  data() {
    return {
      sliderPositionX: 0,
      sliderPositionY: 18,
      selectedElementWidth: 0,
      activeIndex: -1,
      oldIndex: -1,
    }
  },
  computed: {
    filteredLinks() {
      return this.links.filter((x) => (x.shown === undefined ? true : x.shown))
    },
    positionToMoveX() {
      return `${this.sliderPositionX}px`
    },
    positionToMoveY() {
      return `${this.sliderPositionY}px`
    },
    sliderWidth() {
      return `${this.selectedElementWidth}px`
    },
  },
  watch: {
    '$route.path': {
      handler() {
        this.pickLink()
      },
    },
    '$route.query': {
      handler() {
        if (this.query) this.pickLink()
      },
    },
  },
  mounted() {
    window.addEventListener('resize', this.pickLink)
    this.pickLink()
  },
  unmounted() {
    window.removeEventListener('resize', this.pickLink)
  },
  methods: {
    pickLink() {
      this.activeIndex = this.query
        ? this.filteredLinks.findIndex(
          (x) => (x.href === '' ? undefined : x.href) === this.$route.path[this.query]
        )
        : this.filteredLinks.findIndex((x) => x.href === decodeURIComponent(this.$route.path))

      if (this.activeIndex !== -1) {
        this.startAnimation()
      } else {
        this.oldIndex = -1
        this.sliderPositionX = 0
        this.selectedElementWidth = 0
      }
    },
    startAnimation() {
      const el = this.$refs.linkElements[this.activeIndex].$el

      this.sliderPositionX = el.offsetLeft
      this.sliderPositionY = el.offsetTop + el.offsetHeight
      this.selectedElementWidth = el.offsetWidth
    },
  },
}
</script>

<style lang="scss" scoped>
.navigation {
  display: flex;
  flex-direction: row;
  align-items: center;
  grid-gap: 1rem;
  flex-wrap: wrap;
  position: relative;

  .nav-link {
    text-transform: capitalize;
    font-weight: var(--font-weight-bold);
    color: var(--color-text);
    position: relative;

    &:hover {
      color: var(--color-text);

      &::after {
        opacity: 0.4;
      }
    }

    &:active::after {
      opacity: 0.2;
    }

    &.router-link-exact-active {
      color: var(--color-text);

      &::after {
        opacity: 1;
      }
    }
  }

  &.use-animation {
    .nav-link {
      &.is-active::after {
        opacity: 0;
      }
    }
  }

  .nav-indicator {
    position: absolute;
    height: 0.25rem;
    bottom: -5px;
    left: 0;
    width: 3rem;
    transition: all ease-in-out 0.2s;
    border-radius: var(--size-rounded-max);
    background-color: var(--color-brand);

    @media (prefers-reduced-motion) {
      transition: none !important;
    }
  }
}
</style>
