// components/ui/Checkbox.vue
<template>
  <div class="checkbox-outer" :class="{ disabled }" @click="toggle">
    <button class="checkbox" :disabled="disabled" :class="{ checked: value }">
      <CheckIcon v-if="value" />
    </button>
    <p v-if="label">{{ label }}</p>
    <slot v-else />
  </div>
</template>

<script>
import CheckIcon from '~/assets/images/utils/check.svg?inline'

export default {
  name: 'Checkbox',
  components: {
    CheckIcon,
  },
  props: {
    label: {
      type: String,
      default: '',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    value: Boolean,
    clickEvent: {
      type: Function,
      default: () => {},
    },
  },
  methods: {
    toggle() {
      if (!this.disabled) {
        this.$emit('input', !this.value)
      }
    },
  },
}
</script>

<style lang="scss" scoped>
.checkbox-outer {
  display: flex;
  align-items: center;
  cursor: pointer;

  &.disabled {
    opacity: 0.6;
    cursor: not-allowed;

    button {
      cursor: not-allowed;

      &:active,
      &:hover,
      &:focus {
        background-color: var(--color-button-bg);
      }
    }
  }

  p {
    user-select: none;
    padding: 0.2rem 0rem;
    margin: 0;
  }
}

.checkbox {
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;

  width: 1rem;
  height: 1rem;

  padding: 0;
  margin: 0 0.5rem 0 0;

  &.checked {
    background-color: var(--color-brand);
  }

  svg {
    color: var(--color-text-inverted);
    stroke-width: 0.2rem;
    height: 0.8rem;
    width: 0.8rem;
    flex-shrink: 0;
  }
}
</style>

// src/package/components/Checkbox.svelte
<script lang="ts">
    import { uniqueId } from '../utils/uniqueId'
    import IconCheck from 'virtual:icons/heroicons-outline/check'

    export let checked = false;

    const id = `checkbox-${uniqueId()}`
</script>

<div class="checkbox">
    <input type="checkbox" bind:checked={checked} on:change id={id} name={id}>
    <label for={id} class="checkbox__label">
        <span class="checkbox__label__box">
          <IconCheck />
      </span>
        <slot/>
    </label>
</div>

<style lang="postcss">
    .checkbox {
        input {
            display: none;
        }

        display: inline-flex;
        align-items: center;
        grid-gap: 0.5rem;

        &__label {
            display: flex;
            align-items: center;
            gap: 8px;

            > :global(.icon) {
                width: 1.1rem;
                margin-right: -0.1rem;
            }

            &__box {
                height: 1rem;
                width: 1rem;
                display: flex;
                border-radius: 0.25rem;
                background-color: var(--color-button-bg);
                justify-content: center;
                align-items: center;

                > :global(.icon) {
                    display: none;
                    width: 1rem;
                    height: 1rem;
                    color: var(--color-raised-bg)
                }
            }
        }

        [type=checkbox]:checked + label span {
            background-color: var(--color-brand);

            :global(.icon) {
                display: unset;
            }
        }
    }
</style>
