// apps/frontend/src/components/ui/NavRow.vue
<template>
  <nav class="navigation">
    <NuxtLink
      v-for="(link, index) in filteredLinks"
      v-show="link.shown === undefined ? true : link.shown"
      :key="index"
      ref="linkElements"
      :to="query ? (link.href ? `?${query}=${link.href}` : '?') : link.href"
      class="nav-link button-animation"
    >
      <span>{{ link.label }}</span>
    </NuxtLink>
    <div
      class="nav-indicator"
      :style="{
        left: positionToMoveX,
        top: positionToMoveY,
        width: sliderWidth,
        opacity: activeIndex === -1 ? 0 : 1,
      }"
      aria-hidden="true"
    ></div>
  </nav>
</template>

<script setup>
const route = useNativeRoute();

const props = defineProps({
  links: {
    default: () => [],
    type: Array,
  },
  query: {
    default: null,
    type: String,
  },
});

const sliderPositionX = ref(0);
const sliderPositionY = ref(18);
const selectedElementWidth = ref(0);
const activeIndex = ref(-1);
const oldIndex = ref(-1);

const filteredLinks = computed(() =>
  props.links.filter((x) => (x.shown === undefined ? true : x.shown)),
);
const positionToMoveX = computed(() => `${sliderPositionX.value}px`);
const positionToMoveY = computed(() => `${sliderPositionY.value}px`);
const sliderWidth = computed(() => `${selectedElementWidth.value}px`);

function pickLink() {
  activeIndex.value = props.query
    ? filteredLinks.value.findIndex(
        (x) => (x.href === "" ? undefined : x.href) === route.path[props.query],
      )
    : filteredLinks.value.findIndex((x) => x.href === decodeURIComponent(route.path));

  if (activeIndex.value !== -1) {
    startAnimation();
  } else {
    oldIndex.value = -1;
    sliderPositionX.value = 0;
    selectedElementWidth.value = 0;
  }
}

const linkElements = ref();

function startAnimation() {
  const el = linkElements.value[activeIndex.value].$el;

  sliderPositionX.value = el.offsetLeft;
  sliderPositionY.value = el.offsetTop + el.offsetHeight;
  selectedElementWidth.value = el.offsetWidth;
}

onMounted(() => {
  window.addEventListener("resize", pickLink);
  pickLink();
});

onUnmounted(() => {
  window.removeEventListener("resize", pickLink);
});

watch(route, () => pickLink());
</script>

<style lang="scss" scoped>
.navigation {
  display: flex;
  flex-direction: row;
  align-items: center;
  grid-gap: 1rem;
  flex-wrap: wrap;
  position: relative;

  .nav-link {
    text-transform: capitalize;
    font-weight: var(--font-weight-bold);
    color: var(--color-text);
    position: relative;

    &:hover {
      color: var(--color-text);

      &::after {
        opacity: 0.4;
      }
    }

    &:active::after {
      opacity: 0.2;
    }

    &.router-link-exact-active {
      color: var(--color-text);

      &:not(:focus-visible) {
        outline: 2px solid transparent;
        outline-offset: 6px;
        border-radius: 0.25rem;
      }

      &::after {
        opacity: 1;
      }
    }
  }

  &.use-animation {
    .nav-link {
      &.is-active::after {
        opacity: 0;
      }
    }
  }

  .nav-indicator {
    position: absolute;
    height: 0.25rem;
    bottom: -5px;
    left: 0;
    width: 3rem;
    transition: all ease-in-out 0.2s;
    border-radius: var(--size-rounded-max);
    background-color: var(--color-brand);
    outline: 2px solid transparent;
    outline-offset: -2px;

    @media (prefers-reduced-motion) {
      transition: none !important;
    }
  }
}
</style>

// src/components/NavRow.svelte
<script lang="ts">
	import { browser, prerendering } from '$app/env'
	import { page } from '$app/stores'
	import { onDestroy, onMount } from 'svelte'
	import { debounce } from 'throttle-debounce'

	interface Link {
		href: string
		label: string
	}

	export let links: Link[]
	/** Query param name to use (to not use queries, leave this prop blank) */
	export let query = ''

	export let noScroll: true | null = null

	/** Path level in URL, zero-indexed */
	export let level = 0

	let path: string[]
	$: path = [
		...$page.url.pathname
			.substring(1)
			.split('/')
			.map((route) => '/' + route),
		'/',
	]

	$: basePath = path.slice(0, level).join('')

	/* Animation */
	const FAST_TIMING = 'cubic-bezier(1,0,.3,1) -140ms'
	const SLOW_TIMING = 'cubic-bezier(.75,-0.01,.24,.99) -40ms'

	$: activeIndex = query
		? prerendering
			? -1
			: links.findIndex((link) => ($page.url.searchParams.get(query) || '') === link.href)
		: links.findIndex((link) => path[level] === link.href || path[level] === link.href.slice(0, -1))

	let oldIndex = -1

	const linkElements: HTMLAnchorElement[] = []

	const indicator = {
		left: 0,
		right: 0,
		top: 22,
		direction: 'right',
	}

	$: if (activeIndex > -1 && browser && linkElements.length > 0) startAnimation()

	function startAnimation() {
		// Avoids error that `linkElements[activeIndex]` is null
		if (linkElements[activeIndex]) {
			indicator.direction = activeIndex < oldIndex ? 'left' : 'right'

			indicator.left = linkElements[activeIndex].offsetLeft
			indicator.right =
				linkElements[activeIndex].parentElement.offsetWidth -
				linkElements[activeIndex].offsetLeft -
				linkElements[activeIndex].offsetWidth
			indicator.top =
				linkElements[activeIndex].offsetTop + linkElements[activeIndex].offsetHeight - 2
		}

		oldIndex = activeIndex
	}

	const debounced = debounce(100, startAnimation)

	let useAnimation = false

	onMount(() => {
		setTimeout(() => {
			useAnimation = true
		}, 300)

		window.addEventListener('resize', debounced)
	})

	onDestroy(() => {
		if (browser) window.removeEventListener('resize', debounced)
	})
</script>

<nav class="navigation" class:use-animation={useAnimation}>
	{#each links as link, index}
		<a
			href={query
				? link.href
					? `?${query}=${link.href}`
					: '?'
				: level === 0
				? link.href
				: basePath + link.href}
			class="navigation__link"
			class:is-active={index === activeIndex}
			sveltekit:noscroll={noScroll}
			sveltekit:prefetch
			bind:this={linkElements[index]}>
			{link.label}
		</a>
	{/each}
	<div
		class="navigation__indicator"
		style:visibility={useAnimation && activeIndex !== -1 ? 'visible' : 'hidden'}
		style:left={indicator.left + 'px'}
		style:right={indicator.right + 'px'}
		style:top={indicator.top + 'px'}
		style:transition={`left 350ms ${
			indicator.direction === 'left' ? FAST_TIMING : SLOW_TIMING
		},right 350ms ${
			indicator.direction === 'right' ? FAST_TIMING : SLOW_TIMING
		}, top 100ms ease-in-out`} />
</nav>

<style lang="postcss">
	.navigation {
		display: flex;
		flex-direction: row;
		align-items: center;
		grid-gap: 1rem;
		flex-wrap: wrap;
		position: relative;

		&__link {
			font-weight: var(--font-weight-bold);
			color: var(--color-text-light);
			position: relative;

			&::after {
				content: '';
				display: block;
				position: absolute;
				bottom: -2px;
				width: 100%;
				border-radius: var(--rounded-max);
				height: 0.25rem;
				transition: opacity 0.1s ease-in-out;
				background-color: var(--color-brand);
				opacity: 0;
			}

			&:hover {
				color: var(--color-text);

				&::after {
					opacity: 0.4;
				}
			}

			&:active::after {
				opacity: 0.2;
			}

			&.is-active {
				color: var(--color-text);

				&::after {
					opacity: 1;
				}
			}
		}

		&.use-animation {
			.navigation__link {
				&.is-active::after {
					opacity: 0;
				}
			}
		}

		&__indicator {
			position: absolute;
			height: 0.25rem;
			border-radius: var(--rounded-max);
			background-color: var(--color-brand);
			transition-property: left, right, top;
			transition-duration: 350ms;
			visibility: hidden;
		}
	}
</style>
